### ISSUE TITLE
Using fswatch with qt

### ISSUE THREAD

**Issue by asyncer** [emcrisostomo/fswatch#107]
As you may know QtFileSystemWatcher is weak and I need fswatch features in my cross platform app,
Would you please show me how to go through using fswatch in QT C++ code?

**Comment by emcrisostomo** [comment]
I guess you'd like to use `libfswatch`. Have you checked out the `libfswatch` [documentation][doc]? If you're a C++ programmer you'll find your way through the `libfswatch` PDF manual.

[doc]: http://emcrisostomo.github.io/fswatch/documentation.html
