### ISSUE TITLE
fswatch piped into xargs running command twice

### ISSUE THREAD

**Issue by MintyFresh** [emcrisostomo/fswatch#108]
Hello, and thanks in advance for any help

I'm working on an fswatch command and a bash script that will redirect my downloads based on file extension. The issue I'm having is that the script is getting run twice per file. In this case, the script moves the file, so the first run works as expected (the file is successfully moved to a different directory), and then a second call to the script gives a "no such file or directory" error, since the script is looking for the file which is no longer in the downloads folder. I'm on a Mac, OS 10.11.1. Here's what I've got:

# Command:
fswatch -0 --event Created --format="%p%0" Downloads/ | xargs -0 -n 1 bash ./Downloads/dlsort.sh

# dlsort.sh
#!/bin/bash
if (echo "$1" | grep -q '\.jpg$'); then
  mv "$1" Desktop/targdir/
fi

**Comment by emcrisostomo** [comment]
Hi @MintyFresh,

This is documented behaviour of certain monitors, such as the _FSEvents_ monitor you are using on OS X. If different events originate from the same file on a short period of time, then multiple events may carry information about the same event. It's easy to replicate on OS X:

  * Listen on any directory.

  * Create and then immediately remove a file.  You'll get something like this:

        /test/test.txt Created IsFile
        /test/text.txt Created Removed IsFile

`fswatch` cannot do anything about it.  What you can do is just check if the file exists before doing something with it:

    if [ -e "$1" ]; then [your logic here] ; fi

**Comment by AndreasHassing** [comment]
I found this question in search of an answer as to why fswatch runs a command twice when a file has been changed (OS X).

If anyone else stumbles over this, this is what I did:
```bash
$ fswatch -x FileToCheck.x
/this/dir/FileToCheck.x Renamed IsFile
/this/dir/FileToCheck.x Renamed PlatformSpecific AttributeModified IsFile
^C⏎
```

Using the command above I found out that PlatformSpecific is an event that is uniquely fired on file changes. With this information I could use the following command:

```bash
$ fswatch FileToCheck.x -o --event PlatformSpecific | xargs -n1 ./program_to_run_on_filechanged.sh
```

And fswatch executes the program only once.

**Comment by robderon** [comment]
Thanks a lot for this answer.
I'm using mac os 12.6
I wanted to listen only to newly created files. the good event to listen to is Created

Here is my line

fswatch /my/directory -e ".*" -i "\\.jpg$" --event Created | xargs -I{} /usr/local/bin/script to launch {}
