### ISSUE TITLE
Some file changes are not triggering fswatch

### ISSUE THREAD

**Issue by seaside98** [emcrisostomo/fswatch#111]
Using FSEvents on OSX.

I am using fswatch to watch for newly encoded videos on our server. The video is written to a temporary file, and then renamed to the correct file name when the encode is complete. The temporary file's creation and deletion both trigger fswatch, but the renamed file does not. I have also noticed that system log files also don't trigger fswatch when they are written to. Are there certain FSEvent events that you are ignoring, or is this an issue with FSEvents? Any help would be much appreciated.

**Comment by emcrisostomo** [comment]
Hi @seaside98,

`fswatch` is getting all the events without filtering any, unless of course you specify a filter (path, event type or both) yourself. Here's a test run of the latest release on OS X:

```
% fswatch -x ~
/Users/enricomariacrisostomo/before.txt Created IsFile
/Users/enricomariacrisostomo/before.txt Created Renamed IsFile
/Users/enricomariacrisostomo/after.txt Removed Renamed IsFile
```

As you can see, `fswatch` detects the creation of `before.txt` and it's renaming to `after.txt`.

If you still have problems, you should give additional information about what you're doing:

  * How `fswatch` is run.
  * What events are you expecting and which file operations are taking place.
  * Which events are you getting.

Please, reopen this issue with more information.
