### ISSUE TITLE
Libtool library used but 'LIBTOOL' is undefined

### ISSUE THREAD

**Issue by matiaseidis** [emcrisostomo/fswatch#112]
Trying to autogen.sh it I get 

src/libfswatch/Makefile.am:21: error: Libtool library used but 'LIBTOOL' is undefined
src/libfswatch/Makefile.am:21:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
src/libfswatch/Makefile.am:21:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
src/libfswatch/Makefile.am:21:   If 'LT_INIT' is in 'configure.ac', make sure
src/libfswatch/Makefile.am:21:   its definition is in aclocal's search path.
src/libfswatch/Makefile.am: installing 'config/depcomp'
autoreconf: automake failed with exit status: 1

Can you help me with this issue?
I am using ubuntu 15.04 64

Thanks

**Comment by emcrisostomo** [comment]
Hi @matiaseidis, that error usually means that `libtoolize` hasn't ben run and since it should be run by `autogen`, the question is: can you check GNU `libtool` is installed in your system?

**Comment by matiaseidis** [comment]
Hi @emcrisostomo, 
Yes, it is installed

libtool --version
libtool (GNU libtool) 2.4.6
Written by Gordon Matzigkeit, 1996

**Comment by emcrisostomo** [comment]
That's strange indeed.

What happens if you run `libtoolize` manually?

**Comment by matiaseidis** [comment]
same output / results


Thanks

2016-02-12 17:09 GMT+01:00 Enrico Maria Crisostomo <notifications@github.com

**Comment by emcrisostomo** [comment]
Doh! I'm using a Debian VM to develop and test the `inotify` monitor.  I'll have to fire an Ubuntu 15.04 VM to troubleshoot this myself.

**Comment by emcrisostomo** [comment]
Hi @matiaseidis, I've just installed an Ubuntu 15.10 VM, installed the autotools (autoconf, automake, autopoint, libtool and gettext) and run `autogen.sh`.  I'm afraid I found no issues: everything from `autogen.sh` to a complete build runs without issues.  Did you try on a clean Ubuntu installation?

I'm afraid I'm closing this unless further information is provided.

**Comment by emcrisostomo** [comment]
Also, I just noticed that when I asked about `libtoolize` you answered about `libtool`.

**Comment by matiaseidis** [comment]
hey man, thanks for the support.
I answered about libtoolize that time you asked.
I am running debian now, so I will give it a try and let you knwo if any new issue.

Bests
