### ISSUE TITLE
fswatch suddenly stops tracking changes on OSX

### ISSUE THREAD

**Issue by rivaros** [emcrisostomo/fswatch#113]
Weird problem on OSX 10.10.5 Yosemite (fwatch 1.5.1).
Occasionally fswatch stops tracking filesystem changes.
When you run `fswatch .` and then change/add some files in current directory, no output is received.

Killing all instances of fswatch and starting again does not help.
Only solution is rebooting system.

Having this happening like every 7th day actively using fswatch everyday.
Probably it is some system module/process that falls out. 
Do you know what?

**Comment by emcrisostomo** [comment]
Hi @rivaros, thanks for the report, I never experienced this issue.  I'll try to have a look at it.

**Comment by emcrisostomo** [comment]
Unable to replicate.
