### ISSUE TITLE
Install fswatch on iOS and Android

### ISSUE THREAD

**Issue by hellsguardian95** [emcrisostomo/fswatch#115]
Is it possible to install fswatch on the iOS and Android platforms? If yes, how can I achieve the same?

**Comment by emcrisostomo** [comment]
Hi @hellsguardian95:

  * iOS: the `kqueue` monitor may indeed work.  However, porting `fswatch` to iOS doesn't really make sense.  Perhaps you're thinking about using `libfswatch` on iOS: I haven't tried and currently have no plans on doing it.

  * Android: no idea here.

Closing as for the moment.

**Comment by skyerjoe** [comment]
Any good news to this topic  ?

best regards
