### ISSUE TITLE
Event Flag Separator doesn't work

### ISSUE THREAD

**Issue by hellsguardian95** [emcrisostomo/fswatch#116]
I'm trying to separate the event flags using a character/string but it isn't working. 
--event-flag-separator="Any character/string" does not print any event flags let alone separate them.

**Comment by emcrisostomo** [comment]
Hi @hellsguardian95, that option does not turn on event flags. The [documentation] will help you.

Hint:

```
$ fswatch --help 
[...snip...]
 -x, --event-flags     Print the event flags.
[...snip...]
```

[documentation]: http://emcrisostomo.github.io/fswatch/documentation.html

**Comment by emcrisostomo** [comment]
I will change the description of the `--event-flag-separator` option in case it seems to imply that it _also_ turns event flags on.
