### ISSUE TITLE
Events are inconsistent on OSX

### ISSUE THREAD

**Issue by febbraro** [emcrisostomo/fswatch#117]
I have encountered a few interesting things while testing this out on OSX.  The first is that on new command starts for a while all changes are reported as `PlatformSpecific` and then it appears that after a while I start getting proper event notifications for touches and file edits, etc.

Secondly, I am getting `Created` events for both file creations AND deletions.  This, again, sometimes disappears after having run for a while.  I have not had time to dig into the code, yet, but I wanted to put this out there in case others have seen this issue.

I'm on El Capitan 10.11.3 using the default monitor, FSEvents.

**Comment by emcrisostomo** [comment]
Hi @febbraro,

Thanks. The events are reported by `fswatch` exactly as reported by OS X: there is a mapping (which is meant to make `fswatch` report the same events on different platforms) which is pretty coarse at the moment (that's the reason for the existence and abundance of `PlatformSpecific` flags). Apart from that, what you are experiencing is normal OS X behaviour.

As far as deletions are concerned, I guess you are creating and deleting a file within a short period of time. The FSEvents API may report the same event in subsequent notifications and I guess that's what you are observing.

For all the above, I'm closing this issue as regular OS X behaviour.

If, on the other hand, you mean that you are indeed getting an event which has *not* happened while `fswatch` was running, you can reopen this issue again.
