### ISSUE TITLE
v. 1.9.0 breaks the -1 option

### ISSUE THREAD

**Issue by jpeddicord** [emcrisostomo/fswatch#118]
I'm on OS X 10.11.4 and have been using fswatch in some scripts to monitor file changes. After a recent upgrade to 1.9.0 (now 1.9.1), I'm noticing that fswatch doesn't seem to work like it used to; specifically the "-1" flag will hang instead of exiting on a change:

```
~/test $ fswatch -1r .
/Users/peddicor/test/f
^C^C^C^C^C
^\zsh: quit       fswatch -1r .
```
I just ran `touch f` in another window while fswatch was running. Instead of exiting on change, it appears to hang with no response to ^C (SIGQUIT works though). Running without "-1" (and just -r) seems to work fine; it'll keep responding to events and will properly exit on Ctrl-C.

Happy to provide more tests/debugging info if needed.

**Comment by emcrisostomo** [comment]
Hi @jpeddicord, my bad, I acknowledge this is a bug.  Thanks for the report.

**Comment by emcrisostomo** [comment]
Fixed.

**Comment by jpeddicord** [comment]
Thanks for the fix! I appreciate it. 😄
