### ISSUE TITLE
fsw_start_monitor never return while calling from CFFI

### ISSUE THREAD

**Issue by muyinliu** [emcrisostomo/fswatch#126]
I use CFFI(Common Lisp) to wrap **libfswatch**, foreign function `fsw_start_monitor` never return, is it `fsw_start_monitor` a blocked function? Should I wrap `fsw_start_monitor` calls in a thread?

**Comment by emcrisostomo** [comment]
Hi @muyinliu,

Yes, `monitor::start()` and its C wrapper `fsw_start_monitor` are blocking function calls.  You should definitely manage threading yourself if you wanted to invoke them.  It could be as easy as firing the monitor in a separate thread and just rely on the callback to receive change events.
