### ISSUE TITLE
Static library will not have any monitor type available

### ISSUE THREAD

**Issue by Andrepuel** [emcrisostomo/fswatch#142]
The way that monitor types are registered will not work with static libraries. The technique of creating a static object and inserting code in its constructor does not work with static libraries because the linker will discard any symbol that is not used, since no symbol from the file that contains the static constructor is used, the linker assumes it is safe to remove the static construtor at all.
In other projects I've noticed that just by injecting a fake dependency to any function of the file that contains the static constructor will force the linker to include the static constructor. But you would lose the conveniency of easily inserting new monitors to the project.
IMHO I don't think auto registrar should be used at all.

**Comment by deathbaba** [comment]
I'm also stuck with this issue: monitors are not detected in statically built fswatch binary (Ubuntu).
I found the following workaround:
1. Use ```$ make V=1``` to see verbose output
2. Replace final linker command

```$ clang++ -std=gnu++11 -g -O2 -Wall -o fswatch fswatch.o  ../libfswatch/src/libfswatch/.libs/libfswatch.a -lpthread```

by

```$ clang++ -std=gnu++11 -g -Os -Wall -o fswatch fswatch.o  -Wl,-whole-archive ../libfswatch/src/libfswatch/.libs/libfswatch.a -Wl,-no-whole-archive -lpthread```

Notice the ```-Wl,-whole-archive``` parameter. If you also add ```-static``` linker option you will get completely independent static binary (without local .so dependencies).

**Comment by danechitoaie** [comment]
Hi, so what can be doe to build libfswatch statically?

**Comment by noahfriedman** [comment]
I had to do something similar for OS X as of commit c7d894913dfbc4092a33701bf7dc92f52d970a92
Running `make V=1` I see this snippet:

```Making all in fswatch
Making all in src
clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I../..  -I../../libfswatch/src -DLOCALEDIR=\"/usr/local/share/locale\"   -g -O2 -Wall -c -o fswatch.o fswatch.cpp
/bin/sh ../../libtool  --tag=CXX   --mode=link clang++ -std=gnu++11  -g -O2 -Wall   -o fswatch fswatch.o ../../libfswatch/src/libfswatch/libfswatch.la  -lc -lpthread
libtool: link: clang++ -std=gnu++11 -g -O2 -Wall -o fswatch fswatch.o -Wl,-bind_at_load  ../../libfswatch/src/libfswatch/.libs/libfswatch.a -lc -lpthread -framework CoreServices
```

I changed `-Wl,-bind_at_load` to `-Wl,-all_load` in order for the monitors to work.

**Comment by emcrisostomo** [comment]
I agree this is complexity that does not pay us back with any meaningful advantage: I'm removing the monitor registration logic.

**Comment by emcrisostomo** [comment]
It has been closed in `master` and it will be released shortly.
