### ISSUE TITLE
-x option: possible bug?

### ISSUE THREAD

**Issue by JSB97** [emcrisostomo/fswatch#144]
Making use of ```# fswatch 1.9.2 ```, with the following command in directory ```./tmp```.
```
$ fswatch -x .
```
When copying a file from another directory to ```./tmp```,  I get the following output;
```
$ cp somedir/PDF.pdf ./tmp
# somepath/tmp/PDF.pdf Created Removed Updated OwnerModified AttributeModified IsFile
```
When deleting the same file in ```./tmp```,  I get below;
```
$ rm  ./tmp/PDF.pdf
# somepath/tmp/PDF.pdf Created Removed Updated OwnerModified AttributeModified IsFile
```

I would have expected to see ```Created IsFile``` when running ```cp``` and ```Removed IsFile``` upon execution of ```rm```, but is there a reason why I don't observe this?

**Comment by emcrisostomo** [comment]
Are you running `fswatch` on OS X? OS X may return event flags of previous events for the same file if they occur sufficiently close in time.
