### ISSUE TITLE
fswatch doesn't notify on file changes on FreeBSD

### ISSUE THREAD

**Issue by shanavar** [emcrisostomo/fswatch#152]
When I run fswatch it notifies file when a file gets created or removed, but doesn't notify when the file is changed. 

So if I run fswatch with
```
fswatch -o /root | while read num ; \
do \
  echo "notify"
done
```

and then do either `touch /root/test.txt` or `rm /root/test.txt`, then fswatch reacts. If I change a file (e.g. run `echo "test" >> test.txt`) fswatch remains silent.  I installed fswatch through the FreeBSD port provided here (version is 1.7.0.): <https://emcrisostomo.github.io/fswatch/getting.html>

Best wishes,
Patrick

Edit: I just discovered that fswatch acts upon a file change if I start it with the `-r` flag.

**Comment by emcrisostomo** [comment]
Cool, I understand from your edit that this issue can be closed then.

**Comment by hepcat72** [comment]
Noob here.  I don't understand why I don't receive any outputs when I run this on my sqlite reminders database file.  The file is changing when I update reminders in the reminders app, and I can see in `ls` that the lmd is changing, but `fswatch -o -r Data-51254E97-3127-4376-AC09-EC684CE8B64F.sqlite-wal` outputs nothing despite numerous changes to that file.  Am I doing something wrong, or is the method by which the file is altered not monitored by `fswatch`?
