### ISSUE TITLE
Pipe through grep?

### ISSUE THREAD

**Issue by JesseAldridge** [emcrisostomo/fswatch#157]
I'm having some trouble using fswatch + grep + xargs.  I posted a question on StackOverflow:  http://stackoverflow.com/questions/41847120/fswatch-with-grep-not-piping

**Comment by emcrisostomo** [comment]
Hi @JesseAldridge, I answered there.

**Comment by JesseAldridge** [comment]
Cool, thanks man.

**Comment by pbiggar** [comment]
To add a note on this, I had a similar problem with sed. In BSD sed, the flag to line buffer is `-l`, while in gnu sed, the flag is `-s`.

I found that piping fswatch twice (as in `fswatch | cmda | cmdb`)failed under all scenarios unless I found the correct flag for other commands in the pipe. It would be wonderful if there was a way for fswatch to not require this, though I'm not sure that's possible.
