### ISSUE TITLE
add tags, links to alternatives

### ISSUE THREAD

**Issue by josephholsten** [emcrisostomo/fswatch#167]
It wouldn't hurt to let people know about some of the alternatives:
- https://github.com/bevry/watchr
- https://github.com/nroi/waitforfile
- https://github.com/VojtechVitek/rerun
- https://github.com/liudng/dogo
- https://github.com/mattgreen/watchexec

Also tag: `file-watchers`, `filewatcher`

**Comment by emcrisostomo** [comment]
well, that's what Google is for, not `fswatch`
