### ISSUE TITLE
Ubuntu apt-get install fswatch not working

### ISSUE THREAD

**Issue by kamil-kielczewski** [emcrisostomo/fswatch#170]
Please build this tool for ubuntu

**Comment by hadret** [comment]
While https://github.com/emcrisostomo/fswatch/issues/149 is in the works, for the time being:

```
sudo add-apt-repository ppa:hadret/fswatch
sudo apt-get update
sudo apt-get install fswatch
```

**Comment by agaida** [comment]
fswatch has just hit debian/sid - so it will be sooner or later in ubuntu too

**Comment by emcrisostomo** [comment]
Great work. Thanks @agaida.

**Comment by agaida** [comment]
And here it is: https://launchpad.net/ubuntu/+source/fswatch/1.11.2+repack-3

**Comment by emcrisostomo** [comment]
Great job @agaida.

**Comment by stereobooster** [comment]
Hi. Thank you for maintaining this great software. I got an error, maybe you know what the issue here.

I'm trying to install fswatch in ubuntu in Docker

```
FROM blitznote/debase:16.04
RUN apt-get update
RUN apt-get install fswatch
```

but get this

```
E: Unable to locate package fswatch
The command '/bin/bash -c apt-get install fswatch' returned a non-zero code: 100
```

**Comment by hadret** [comment]
@stereobooster fswatch was introduced only in the upcoming Ubuntu release, 18.04: https://packages.ubuntu.com/search?keywords=fswatch

**Comment by niftylettuce** [comment]
Can we add a note to the README regarding `sudo apt-get install fswatch`?

**Comment by reubano** [comment]
Please add this info to the readme.
