### ISSUE TITLE
--event <numeric event flags bitmask>

### ISSUE THREAD

**Issue by karog** [emcrisostomo/fswatch#174]
It would be nice if the --event option would take as argument the event flags numeric bitmask so that several event types could be combined in a single argument/option. For example,

--event 30

instead of

--event Created --event Updated --event Removed --event Renamed

**Comment by emcrisostomo** [comment]
Hi @karog, I think this is a nice feature. I've scheduled it for the next release.

**Comment by emcrisostomo** [comment]
Merged to `master`.
