### ISSUE TITLE
libfswatch:  calling fsw_add_path() after fsw_start_monitor()

### ISSUE THREAD

**Issue by wolfchimneyrock** [emcrisostomo/fswatch#179]
Hi,
I am using libfswatch in a project on linux.  Is there a way to dynamically add new paths to the monitor after it has been started?  
Right now I it does not have the desired effect, i.e. running fsw_add_path() after fsw_start_monitor() does not start monitoring changes on that new path.

Do I need to re-run fsw_start_monitor() after adding new paths?  I am concerned about a big potential performance hit as it is possible there could be a lot of directories changed as the program is running, and I'm not sure how much work fsw_start_monitor() is doing.

**Comment by t3hk0d3** [comment]
You have to just stop monitor (`fsw_stop_monitor()`), and start it again (`fsw_start_monitor()`).

**Comment by emcrisostomo** [comment]
Thanks @t3hk0d3

**Comment by wangchuanfang** [comment]
I use fswatch_test demo . but, 
"  if (FSW_OK != fsw_start_monitor(*handle))
  {
    fprintf(stderr, " Error creating thread\n");
  }
" 
The fsw_start_monitor always reutrun failed. This is why？？

**Comment by sxzxs** [comment]
An event will be missed between start and stop.
