### ISSUE TITLE
Check the capabilities of date before using --utc and --date

### ISSUE THREAD

**Issue by emcrisostomo** [emcrisostomo/fswatch#193]
#192 introduced the following change:

```
MAN_DATE=$(date +'%B %d, %Y')
if test -n "$SOURCE_DATE_EPOCH"; then
  MAN_DATE=$(LC_ALL=C date --utc --date=@$SOURCE_DATE_EPOCH +'%B %d, %Y')
fi
```

However, `date` capabilities are not checked and invocation may fail in platforms where `--utc` and `--date` are not supported.

**Comment by t3hk0d3** [comment]
Synonym for BSD date would be following command:

```
MAN_DATE=$(LC_ALL=C TZ=UTC date -r $SOURCE_DATE_EPOCH +'%B %d, %Y')
```

**Comment by emcrisostomo** [comment]
Thank you very much @t3hk0d3

**Comment by t3hk0d3** [comment]
@emcrisostomo 
Isn't this one could be closed?

**Comment by emcrisostomo** [comment]
Hi @t3hk0d3, yes, it can be closed: I left it open because I wanted to configure and build it in all the supported OS and this wasn't assigned to any milestone.
