### ISSUE TITLE
json format output

### ISSUE THREAD

**Issue by t3hk0d3** [emcrisostomo/fswatch#194]
It would be nice to have that in fswatch tool itself, but honestly - it have very limited use cases.

Basically idea is to have something like this:

```zsh
$ fswatch -json .
[
{ "path": "foo/bar", "timestamp": 1233543, "flags": ["isFile", "Modified"] },
{ "path": "foo/bar1", "timestamp": 1233553, "flags": ["isFile", "Modified"] },
{ "path": "foo/bar2", "timestamp": 1233563, "flags": ["isFile", "Modified"] },
{ "path": "foo/bar3", "timestamp": 1233573, "flags": ["isFile", "Modified"] },
...
]
```

That would allow to stream/log events in effortlessly-machine-readible format.

Is it worth implementing? Any additional ideas?

**Comment by emcrisostomo** [comment]
Hi @t3hk0d3,

Actually you can get something very similar already with:

```
fswatch -r --format="{\"path\": \"%p\", \"timestamp\":\"%t\", \"flag\": \"%f\"}" path
{"path": "/Users/enrico/temp/test.txt", "timestamp":"Mon Dec 11 23:18:35 2017", "flag": "Created IsFile"}
```

Flags are not bubbled-up in an array, and you get a space-separated element instead. I could improve the format to be able to specify the event-type separator, but I'm not sure whether that's a top priority one.
