### ISSUE TITLE
Merging keyboard button hits with fswatch events?

### ISSUE THREAD

**Issue by ebraminio** [emcrisostomo/fswatch#199]
Is it possible to have keyboard events also as a source of events? I like to integrate fswatch on the development of [a known project](https://github.com/harfbuzz/harfbuzz/pull/796) and am wondering if is possible in addition to rebuilding the project with file changes it would be possible to run the test suit with some short key like "t" or something.

I tried some bash script based solution like some of the ones mentioned [here](https://serverfault.com/q/171095) with no success.

**Comment by emcrisostomo** [comment]
Hi @ebraminio,

Perhaps it would be easier to make `fswatch` react to a signal such as `SIGINFO`. This way you could send a signal to it (`SIGINFO` can be sent with `CTRL-T`) and have `fswatch` synthesise a file system change event for it.
