### ISSUE TITLE
Release 1.12.0

### ISSUE THREAD

**Issue by t3hk0d3** [emcrisostomo/fswatch#204]
There is quite a lot of changes since last release, it would be great if you release next version.

Thank you!

**Comment by jstarcher** [comment]
I second!

**Comment by emcrisostomo** [comment]
Hi, I agree. This is lagging behind because I'm quite busy at the moment and I wanted to include a couple of features and do some thorough testing before releasing.

**Comment by emcrisostomo** [comment]
Thanks @t3hk0d3 I'll let you know.

**Comment by t3hk0d3** [comment]
Thanks for release!
