### ISSUE TITLE
gcc 4.4.7 compile and install fswatch by source

### ISSUE THREAD

**Issue by mihongkun** [emcrisostomo/fswatch#208]
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

error info:

checking where the gettext function comes from... libc
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=gnu++11... no
checking whether g++ supports C++11 features with -std=gnu++0x... no
checking whether g++ supports C++11 features with -std=c++11... no
checking whether g++ supports C++11 features with +std=c++11... no
checking whether g++ supports C++11 features with -h std=c++11... no
checking whether g++ supports C++11 features with -std=c++0x... no
checking whether g++ supports C++11 features with +std=c++0x... no
checking whether g++ supports C++11 features with -h std=c++0x... no
configure: error: *** A compiler with support for C++11 language features is required.

**Comment by t3hk0d3** [comment]
AFAIK you need at least GCC 4.7 for C++11 support - 

https://gcc.gnu.org/gcc-4.7/cxx0x_status.html

However you might try to lower it to c++0x and check if it compiles.

**Comment by mihongkun** [comment]
@t3hk0d3  thank you.

**Comment by emcrisostomo** [comment]
Thanks @t3hk0d3
