### ISSUE TITLE
How to watch a directory or files by mask with poll_monitor (NFS/FUSE)?

### ISSUE THREAD

**Issue by Vanav** [emcrisostomo/fswatch#209]
I need to monitor a directory or file mask like "*.conf" in poll_monitor mode, because I use NFS/FUSE that doesn't support any notification events (Gluster FUSE mount). But it doesn't work, only exact existing file path works.
Is it possible to watch directory/file mask in poll_monitor mode?

Works only for existing files because of shell wildcard support:
```fswatch --monitor=poll_monitor --one-per-batch /mnt/conf/nginx/conf.d/*```
Doesn't work:
```fswatch --monitor=poll_monitor --one-per-batch /mnt/conf/nginx/conf.d/```

**Comment by emcrisostomo** [comment]
`fswatch` does _not_ recursively watch a directory. The shell glob pattern in the first command results in `fswatch` being fed as many arguments as files are there in that directory. If you want to recursively scan a directory, use the appropriate option: `-r`.
