### ISSUE TITLE
GCC 4.8 does not have proper regex support

### ISSUE THREAD

**Issue by chpatton013** [emcrisostomo/fswatch#210]
I built the most recent release of `fswatch` on Ubuntu 14.04 with GCC 4.8.4. This compiles just fine, but yields a version of `fswatch` that does not have functioning regex support. The implementation of `std::regex_search` in the STL provided by GCC 4.8.4 looks something like this:
```
template <...>
bool regex_search(...) {
  return false;
}
```

This makes for a very opaque and frustrating debugging experience while using `fswatch`, since every regex filter you provide fails with no useful output. To save other people this trouble in the future, please add a minimum version check for GCC to ensure that regex support is actually available.

**Comment by emcrisostomo** [comment]
I was _not_ aware of this pitfall. I will have a look at it.

**Comment by emcrisostomo** [comment]
This check should now be in `master`. I'll test it on Linux tomorrow.

**Comment by emcrisostomo** [comment]
> GCC 4.8 has a lot unfortunate bugs. I'm actually surprised they decided to release that build.

Yes, I've made a quick Google search and you're not the only one that has been bitten by the broken `<regex>` implementation. Unfortunate.

**Comment by emcrisostomo** [comment]
A check has been added which rejects GCC 4.8.
