### ISSUE TITLE
--exclude doesn't work?

### ISSUE THREAD

**Issue by netjune** [emcrisostomo/fswatch#213]
I tried the followings, they all didn't ignore the file "test.sh".
```
fswatch -r -t -x --exclude '.*\.sh' .
fswatch -r -t -x --exclude '.*\\.sh' .
fswatch -r -t -x --exclude '*.sh' .
fswatch -r -t -x --exclude '*sh' .
```

**Comment by emcrisostomo** [comment]
There's not sufficient information to troubleshoot this (OS, monitor, unexpected output).

**Comment by emcrisostomo** [comment]
Just as an idea, please check #210 and see whether that may be happening to you.
