### ISSUE TITLE
Exclude all doesn't work as expected

### ISSUE THREAD

**Issue by Vanav** [emcrisostomo/fswatch#219]
Example:
```
fswatch --exclude='.*' --include='myfile' -v /tmp/test
```
Expected: exclude all, but include only `/tmp/test/myfile`.
Actual: excludes all, doesn't ever monitors the path `/tmp/test`.

Documentation says:
```
The following filter file instructs fswatch to ignore all files except those ending in ‘.cpp’, ignoring case.

- .*
+i \.cpp$
```
(http://emcrisostomo.github.io/fswatch/doc/1.14.0/fswatch.html/Invoking-fswatch.html#Filtering-by-Path)
so I think the example should work correctly.

Log:
```
register_signal_handlers: SIGTERM handler registered.
register_signal_handlers: SIGABRT handler registered.
register_signal_handlers: SIGINT handler registered.
start_monitor: Adding path: /tmp/test
```
Notice, there is no line:
```
add_watch: Added: /tmp/test
```
fswatch 1.14.0, gcc 4.9.2, tested monitors: inotify, poll.

**Comment by emcrisostomo** [comment]
Hi @Vanav,

The second statement of the section of the documentation you're citing, says:

> Sometimes, the exclusion of a path may result in the exclusion of an object from the list of monitored objects

which is _exactly_ what's happening to you. The list of object to monitor is `(/tmp/test)` and the filters you're using _exclude_ it, so nothing gets actually monitored.

**Comment by Vanav** [comment]
How can I solve this two usecases:
1. Monitor `/tmp/test` directory, exclude everything, include only `\.cpp$`?
2. Monitor `/tmp/test` directory, exclude notifications about directory `/tmp/test` itself?

About second usecase: I monitor FUSE mount with `poll_monitor` and on `modifiedfile` file change I have such log:
```
# fswatch --monitor=poll_monitor -r -v -t -x /mnt/conf/test
register_signal_handlers: SIGTERM handler registered.
register_signal_handlers: SIGABRT handler registered.
register_signal_handlers: SIGINT handler registered.
start_monitor: Adding path: /mnt/conf/test
run: Done scanning.
notify_events: Notifying events #: 2.
Wed 05 Dec 2018 02:58:50 PM MSK /mnt/conf/test AttributeModified
Wed 05 Dec 2018 02:58:50 PM MSK /mnt/conf/test/modifiedfile Updated AttributeModified
run: Done scanning.
notify_events: Notifying events #: 2.
Wed 05 Dec 2018 02:58:52 PM MSK /mnt/conf/test AttributeModified
Wed 05 Dec 2018 02:58:52 PM MSK /mnt/conf/test/modifiedfile Updated AttributeModified
run: Done scanning.
^Cclose_handler: Executing termination handler.
stop: Stopping the monitor.
start: Inactivity notification thread: joining
```
Is there a way to filter out `/mnt/conf/test` to keep output cleaner?

**Comment by azman0101** [comment]
I've exactly the same issue
