### ISSUE TITLE
Fedora fswatch package

### ISSUE THREAD

**Issue by jgkamat** [emcrisostomo/fswatch#223]
It would be really nice to have a package for fswatch on fedora (or even just an RPM we can install).

Similar to https://github.com/emcrisostomo/fswatch/issues/149

**Comment by dagostinelli** [comment]
It's been a year since this was mentioned, I assume that @emcrisostomo need some help (in terms of spare time)  Perhaps if someone gets the ball going. 

[I happen to be a maintainer for Fedora](https://fedoraproject.org/wiki/User:Dagostinelli) and like to use fswatch in my work.  I can start the process @emcrisostomo

**Comment by emcrisostomo** [comment]
@dagostinelli, that would be _awesome_. Actually, I need help both in terms of spare time and in term of knowledge: I'm not using any OS that uses the RPM package management system and that's why this issue has been sitting here so long.

**Comment by dagostinelli** [comment]
@emcrisostomo Great! I'll get started.  ETA: would be in about 3-10 days (I have to work it into my schedule) This shall be done!

**Comment by dagostinelli** [comment]
Can you email me?  I have some questions and things to discuss. [My email address can be found here.](https://fedoraproject.org/wiki/User:Dagostinelli)  

BTW, I looked up yours on your web site, but the link to de-obfuscate it is broken.

**Comment by emcrisostomo** [comment]
Hi @dagostinelli, I've just sent you an email.

**Comment by emcrisostomo** [comment]
@dagostinelli, thanks for your contribution!

**Comment by MarshallAsch** [comment]
Any update on the progress of making an rpm package for Fedora?

**Comment by dagostinelli** [comment]
@MarshallAsch Soon.

https://bugzilla.redhat.com/show_bug.cgi?id=1827880

**Comment by dagostinelli** [comment]
Almost there.

https://bodhi.fedoraproject.org/updates/?packages=fswatch

**Comment by aDotInTheVoid** [comment]
This is [stable now](https://bodhi.fedoraproject.org/updates/FEDORA-2020-4d76bed500).

**Comment by dagostinelli** [comment]
Great news!  It's now available for Fedora, Centos8 and RHEL8!

```
$ sudo dnf install fswatch
[sudo] password for dagostinelli: 
Last metadata expiration check: 1:29:14 ago on Thu 25 Jun 2020 02:51:46 PM CDT.
Dependencies resolved.
=======================================================================================================================
 Package                   Architecture             Version                            Repository                 Size
=======================================================================================================================
Installing:
 fswatch                   x86_64                   1.14.0-3.fc32                      updates                   177 k

Transaction Summary
=======================================================================================================================
Install  1 Package

Total download size: 177 k
Installed size: 585 k
Is this ok [y/N]: 

```

**Comment by thoni56** [comment]
So this should probably be closed now?

**Comment by dagostinelli** [comment]
Agreed

**Comment by emcrisostomo** [comment]
Thanks everybody, thanks @dagostinelli
