### ISSUE TITLE
Using fswatch to detect new files (Solaris)

### ISSUE THREAD

**Issue by SteveHallNNT** [emcrisostomo/fswatch#228]
Hi,

Can I use fswatch to detect when a file is created in a folder on Solaris?  When I monitor a folder it does tell me the folder has changed when I add a file but it doesn't seem to have any details of the new file itself.  Changing a pre-existing file works and deleting a file seems OK too.  

Disclaimer : when I compiled it I had to comment out references to FILE_TRUNC in fen_monitor.cpp as the compiler didn't seem to know where they were defined.  Is this relevant?

Many thanks
Steve H

**Comment by foxx** [comment]
Also had to comment these lines out to make `fswatch` work on Solaris. I'll report back with a PR if it seems stable.

**Comment by SteveHallNNT** [comment]
@foxx - can you detect new files being created on Solaris?

**Comment by foxx** [comment]
@SteveHallNNT Yeah, Solaris 11 has something3 called [File Events Notification](https://blogs.oracle.com/solaris/file-notification-in-opensolaris-and-a-bit-of-shell-internals-v2). 

There does appear to be support in this library for Solaris too, based on the `README`;

> A monitor based on the File Events Notification API of the Solaris kernel and its derivatives.

I haven't tested this library individually, but it seems to be working fine with `minio`.

**Comment by emcrisostomo** [comment]
The behaviour depends on the monitor. Solaris File Events Notification will tell you that a directory has changed when a file has been created, but won't give you any more details. It's up to the receiver to scan the directory contents and see what file has been created.
