### ISSUE TITLE
really slow on macos

### ISSUE THREAD

**Issue by iwelch** [emcrisostomo/fswatch#230]
hi enrico---in the docs, you probably want to change "OS X" to "macos" now.

even with a latency request of 0.2, fswatch sometimes takes several seconds.  Other apps, liked Marked 2 (https://marked2app.com/) are always instant, using fsevents.

regards, /iaw

**Comment by emcrisostomo** [comment]
Thank you very much @iwelch: in fact `fswatch` doesn't allow you to specify the `kFSEventStreamCreateFlagNoDefer` flag (`libfswatch` does):

Here is [the documentation](https://developer.apple.com/documentation/coreservices/1455376-fseventstreamcreateflags/kfseventstreamcreateflagnodefer?language=objc) and the rationale for the behaviour of `fswatch` is:

> This is the default behavior and is more appropriate for background, daemon or batch processing apps.

I'm marking this as an enhancement.

**Comment by iwelch** [comment]
Suggestion: If fswatch is running on a tty, make fast check the update.  if fswatch is invoked in batch, make slow check the update.  (and maybe allow a flag to toggle.)

**Comment by emcrisostomo** [comment]
Thanks, that's a good suggestion indeed.

**Comment by emcrisostomo** [comment]
This has been implemented in `master`. Thanks @iwelch
