### ISSUE TITLE
"inotify_add_watch: No space left on device" error when using "event" param

### ISSUE THREAD

**Issue by unoexperto** [emcrisostomo/fswatch#232]
Could you please suggest right way to filter by event types ?

I've tried this

```
sudo fswatch --event Updated -xr -d /home/expert/
```

By default on my Ubuntu MATE 19.04 (kernel 5.0.0-25-generic) I get errors 

```
inotify_add_watch: No space left on device
inotify_add_watch: No space left on device
inotify_add_watch: No space left on device
inotify_add_watch: No space left on device
inotify_add_watch: No space left on device
inotify_add_watch: No space left on device
inotify_add_watch: No space left on device
inotify_add_watch: No space left on device
```

So I checked output of `cat /proc/sys/fs/inotify/max_user_watches` and it's 8192. I changed it via `sudo sysctl fs.inotify.max_user_watches=1048576` but fswatch seems to hang now. But after long long wait exits with

```
Event queue overflow.
Status code: 1
```

Please advise, @emcrisostomo

I believe we can link this ticket to #153.

**Comment by rualark** [comment]
I also have this error:
`
inotify_add_watch: No space left on device
`

**Comment by emcrisostomo** [comment]
I'm not able to reproduce it.
