### ISSUE TITLE
fswatch doesn't notice file changes predictably

### ISSUE THREAD

**Issue by itmuckel** [emcrisostomo/fswatch#234]
Hello!
I created a Dockerfile based on php:7.3-apache in which I installed fswatch via apt (version 1.14.0).
Now I run this script inside docker:
```bash
# Build the website on file changes
fswatch --allow-overflow --print0 --event=AttributeModified --one-per-batch --recursive data content layouts themes static | {
  while read event; do
    echo "Rebuilding Website..."
    ./build.sh
  done
}
```

Unfortunately most of the time it doesn't recognize any file changes. Any idea why?

I already increased the file watcher count on my host system (Ubuntu 18.04.3).

**Comment by emcrisostomo** [comment]
Nope. Can you provide the simplest test scenario where this fails?
