### ISSUE TITLE
Doesn't work with crontab

### ISSUE THREAD

**Issue by JamesHopbourn** [emcrisostomo/fswatch#235]
sh script:
```
fswatch ~/Desktop/1 | while read file
do
rsync -trl --delete ~/Desktop/1 ~/Desktop/2
now=$(date +"%T")
echo "⚠️  $now ${file} synced"
done
```

It can work well by command: nohup ./sync.sh &.
But I want to us crontab to launch sh script automator and add this to crontab file:
```
@reboot (nohup zsh $HOME/Desktop/sync.sh &)
```

But it doesn't work.

**Comment by emcrisostomo** [comment]
Are you sure fswatch is in the path expected by your cron job?
