### ISSUE TITLE
Does this no longer take a command to run on file changes?

### ISSUE THREAD

**Issue by bwiklund** [emcrisostomo/fswatch#24]
I just upgraded, and `fswatch . "./foo"` doesn't run `foo` anymore, it just prints out a list of the files changes.

**Comment by semaperepelitsa** [comment]
If anyone is interested to just run a command without passing changed files, you need to replace this:

```
$ fswatch . | xargs -n1 echo updated
updated /path/to/file
updated /path/to/file
updated /path/to/file
```

With this:

```
$ fswatch -o . | xargs -n1 -I "{}" echo updated
updated
updated
updated
```

Substitute "echo updated" with your own command.
