### ISSUE TITLE
Erro compiling in Raspberry Pi 3b (not 3b+)

### ISSUE THREAD

**Issue by adrianrb** [emcrisostomo/fswatch#242]
When compiling from source in my RPi 3b (no apt package found), I´m finding erros below.
Missing dependency?

Edit: Using 2019-09-26-raspbian-buster.zip from raspberrypi.org

`pi@raspberrypi:~/fswatch-1.9.3 $ make
make  all-recursive
make[1]: Entering directory '/home/pi/fswatch-1.9.3'
Making all in libfswatch
make[2]: Entering directory '/home/pi/fswatch-1.9.3/libfswatch'
make  all-recursive
make[3]: Entering directory '/home/pi/fswatch-1.9.3/libfswatch'
Making all in src
make[4]: Entering directory '/home/pi/fswatch-1.9.3/libfswatch/src'
Making all in libfswatch
make[5]: Entering directory '/home/pi/fswatch-1.9.3/libfswatch/src/libfswatch'
  CXX      c/cevent.lo
  CXX      c/libfswatch.lo
  CXX      c/libfswatch_log.lo
  CXX      c++/libfswatch_exception.lo
  CXX      c++/event.lo
  CXX      c++/monitor.lo
  CXX      c++/poll_monitor.lo
  CXX      c++/path_utils.lo
  CXX      c++/string/string_utils.lo
  CXX      c++/inotify_monitor.lo
  CXXLD    libfswatch.la
ar: `u' modifier ignored since `D' is the default (see `U')
make[5]: Leaving directory '/home/pi/fswatch-1.9.3/libfswatch/src/libfswatch'
make[5]: Entering directory '/home/pi/fswatch-1.9.3/libfswatch/src'
make[5]: Nothing to be done for 'all-am'.
make[5]: Leaving directory '/home/pi/fswatch-1.9.3/libfswatch/src'
make[4]: Leaving directory '/home/pi/fswatch-1.9.3/libfswatch/src'
Making all in po
make[4]: Entering directory '/home/pi/fswatch-1.9.3/libfswatch/po'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/pi/fswatch-1.9.3/libfswatch/po'
Making all in doc
make[4]: Entering directory '/home/pi/fswatch-1.9.3/libfswatch/doc'
Making all in doxygen
make[5]: Entering directory '/home/pi/fswatch-1.9.3/libfswatch/doc/doxygen'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/pi/fswatch-1.9.3/libfswatch/doc/doxygen'
make[5]: Entering directory '/home/pi/fswatch-1.9.3/libfswatch/doc'
make[5]: Nothing to be done for 'all-am'.
make[5]: Leaving directory '/home/pi/fswatch-1.9.3/libfswatch/doc'
make[4]: Leaving directory '/home/pi/fswatch-1.9.3/libfswatch/doc'
make[4]: Entering directory '/home/pi/fswatch-1.9.3/libfswatch'
make[4]: Leaving directory '/home/pi/fswatch-1.9.3/libfswatch'
make[3]: Leaving directory '/home/pi/fswatch-1.9.3/libfswatch'
make[2]: Leaving directory '/home/pi/fswatch-1.9.3/libfswatch'
Making all in src
make[2]: Entering directory '/home/pi/fswatch-1.9.3/src'
  CXX      fswatch.o
  CXXLD    fswatch
/usr/bin/ld: ../libfswatch/src/libfswatch/.libs/libfswatch.so: undefined reference to `__atomic_load_8'
/usr/bin/ld: ../libfswatch/src/libfswatch/.libs/libfswatch.so: undefined reference to `__atomic_store_8'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:485: fswatch] Error 1
make[2]: Leaving directory '/home/pi/fswatch-1.9.3/src'
make[1]: *** [Makefile:572: all-recursive] Error 1
make[1]: Leaving directory '/home/pi/fswatch-1.9.3'
make: *** [Makefile:438: all] Error 2
pi@raspberrypi:~/fswatch-1.9.3 $
`

**Comment by emcrisostomo** [comment]
I never compiled `fswatch` on a Raspberry Pi: I don't even own one, and I can't try. However, it looks like the linker needs to be instructed to search for an additional library on the library search path (perhaps `-latomic`?)

Let us know!
