### ISSUE TITLE
Feature: Option to exit non-zero when interrupted

### ISSUE THREAD

**Issue by douglasdd** [emcrisostomo/fswatch#245]
The man page clearly says

    When it receives a SIGABRT, SIGINT or SIGTERM signal, fswatch
    closes the notification streams and exits gracefully returning 0 to the calling process.

However a flag to let fswatch exit with non-0 when signaled would make some shell scripting use cases less painful....

Typically when developing, I write a quick loop like this (bash) and leave it running in a background shell:

    while fswatch -1 src/... ; do
        check_syntax && \
        run_tests    && \
        echo OK      || echo FAILED
        date "+%Y-%m-%d_%H-%M-%S"
    done

BUT when I `^C` to kill the loop (waiting at fswatch), fswatch exists with success and the loop immediately continues executing again.  So I have to ^C multiple times to get the prompt back and make whatever change.

This kind of change would have to be flag-protected to be sure that we don't break existing users.  Some possible flags / suggested implementations:
* `--abort-on-signal` -- error exit on any signal
* `--abort-on-signals=INT,QUIT`  -- error exit only on specified signals

**Comment by la-ruby** [comment]
I have the same issue, 
@douglasdd has migrated to something better?

**Comment by DabeDotCom** [comment]
I stubbed my toe on this recently, too...

IMHO, if you're using `-1`, then `^C` **should** return failure, always.

Returning 0 in "infinite loop" mode makes total sense — killing the process is the "normal" way for it to exit, and _you_ want to know if it died for some OTHER reason — but when I'm **asking** for "one" event, I'm expecting "one" event, and if it was `kill(1)`-ed beforehand, that's a problem and I want to know about it.

The current behavior violates the [Principle of Least Astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).


Anyway, I've submitted a "Simplest Thing That Can Possibly Work" PR: #313

- https://github.com/emcrisostomo/fswatch/compare/master...DabeDotCom:fswatch:one-event-exit-signal

**Comment by emcrisostomo** [comment]
Thanks @DabeDotCom , I agree with you. It makes more sense to adhere to this convention, and ensures `fswatch` behaves predictably with other Unix utilities in `-1` mode.

Just merge into `master`
