### ISSUE TITLE
Remove mention to fswatch-run from the man page

### ISSUE THREAD

**Issue by nickodell** [emcrisostomo/fswatch#249]
The man page [mentions](https://github.com/emcrisostomo/fswatch/blob/1f52bc9d370a24137313a83dfca72351e3f3f71b/man/fswatch.7.in#L513) a command called fswatch-run:

```
     Although we encourage you to embrace the new fswatch behaviour and update your scripts, we provide a
     little wrapper called fswatch-run which is installed alongside fswatch which lets you use the legacy
     syntax:

           $ fswatch-run path [paths] program

     Under the hood, fswatch-run simply calls fswatch -o piping its output to xargs.

     fswatch-run is a symbolic link to a shell-specific wrapper.  Currently, ZSH and Bash scripts are pro-
     vided.  If no suitable shells are found in the target system, the fswatch-run symbolic link is not cre-
     ated.
```

According to the changelog, this was removed in 1.5.1:

https://github.com/emcrisostomo/fswatch/blob/1f52bc9d370a24137313a83dfca72351e3f3f71b/NEWS#L104-L110

Please update the documentation so that people like me don't go searching for a command which does not exist. Better yet, bring the command back!

**Comment by emcrisostomo** [comment]
Thanks @nickodell
