### ISSUE TITLE
-1 flag prints the file changed 3x before exiting

### ISSUE THREAD

**Issue by jleider** [emcrisostomo/fswatch#256]
Ubuntu 20.04, fswatch 1.14.0

Even with the `-1` flag I get 3x the number of lines output vs on mac where I only see 1.

```
On Linux
$ fswatch -1 /path
/path/file.ext
/path/file.ext
/path/file.ext

On Mac:
$ fswatch -1 /path
/path/file.ext
```

This might be related to #255

**Comment by emcrisostomo** [comment]
Different OS behave differently, output can't be guaranteed to be the same. Have you tried printing the event flags to see what's being reported?

**Comment by emcrisostomo** [comment]
See #255 (fixed in master)
