### ISSUE TITLE
fswatch based tool to put files in YYYY-MM-DD folders

### ISSUE THREAD

**Issue by kaihendry** [emcrisostomo/fswatch#264]
Hi, I'm looking for a utility like what I have here https://github.com/kaihendry/dotfiles/blob/master/dl/manage.sh where files that are dumped into ~/Downloads or ~/Desktop on MacOS machine are moved to a ~/dl/YYYY-MM-DD folder, for better organization.

Is there such a thing that exists already?

**Comment by emcrisostomo** [comment]
Not that I know of. Interesting use case. Have you solved it?
