### ISSUE TITLE
macOS and linux: no way to correlate rename events

### ISSUE THREAD

**Issue by christian-schulze** [emcrisostomo/fswatch#278]
File move operations on MacOS are reported by `fswatch` as pairs of `Renamed` events. The first event being the source and the second event being the destination.

Given the following scenario, the events are not reported in the correct order:
```bash
touch a 1; mv a b; mv 1 2; mv b c; mv 2 3
```

Actual output:
> 1)  a -> CREATED RENAMED IS_FILE
> 2) 1 -> CREATED RENAMED IS_FILE
> 3) b -> RENAMED IS_FILE
> 4) c -> RENAMED IS_FILE
> 5) 2 -> RENAMED IS_FILE
> 6) 3 -> RENAMED IS_FILE

Given these results, there is no way to correlate event 3 with 1, and event 5 with 2.

If the `Created` and `Renamed` events were not merged into one event, then this might behave as expected. Is this something that fswatch is doing explicitly? Or is this what the MacOS API is reporting?

**Comment by emcrisostomo** [comment]
This is exactly what the macOS API is reporting, I'm afraid. There should be a way to correlate multiple rename events using `inode` identifiers (available since macOS 10.13 High Sierra IIRC), but I haven't looked into it yet.

**Comment by christian-schulze** [comment]
@emcrisostomo yes agreed, I've actually patched the `fsevents` node module to support this:
https://github.com/fsevents/fsevents/pull/360

**Comment by emcrisostomo** [comment]
Thanks for the feedback @christian-schulze

**Comment by emcrisostomo** [comment]
I've update the issue since I've fixed this in the feature branch for both the `fsevents_monitor` and the `inotify_monitor`.

**Comment by emcrisostomo** [comment]
Merged into `master`.
