### ISSUE TITLE
fswatch-git is broken in AUR

### ISSUE THREAD

**Issue by ClayShoaf** [emcrisostomo/fswatch#288]
Trying to install with `yay` AUR helper and it exits with the following error message:

```
rm: cannot remove 'README.osx': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
 -> error making: fswatch-git
```

**Comment by emcrisostomo** [comment]
I'm afraid I'm not maintaining the `yay` package, you should try to contact with the package maintainer.
