### ISSUE TITLE
Support Solaris/Illumos File Events Notification API

### ISSUE THREAD

**Issue by josephholsten** [emcrisostomo/fswatch#35]
Described here: https://blogs.oracle.com/praks/entry/file_events_notification

**Comment by AlainODea** [comment]
Here's an example of someone building a user land program like **inotify-tools** or **fswatch** on File Events Notification based on the article @josephholsten shared:
https://solarisrants.wordpress.com/2013/07/24/solaris-file-event-notification/

**Comment by emcrisostomo** [comment]
Thanks @AlainODea, that's helpful.

**Comment by emcrisostomo** [comment]
Development has effectively moved to #99.
