### ISSUE TITLE
support file-content change watching

### ISSUE THREAD

**Issue by josephholsten** [emcrisostomo/fswatch#37]
Many times an application is interested not in the fact that the modified date changed, but that the actual content of the file changed.

Obviously this does not apply to directories, and adds a whole new set of edge cases to deal with. Is this something which makes sense as part of fswatch, or should it be a separate tool?

**Comment by emcrisostomo** [comment]
I thought about this one @josephholsten and I see no way I can do this into `fswatch` and achieve some level of portability.
