### ISSUE TITLE
install fswatch via aptitude/apt-get

### ISSUE THREAD

**Issue by slang800** [emcrisostomo/fswatch#47]
releasing a debian package would be really helpful for linux users

**Comment by hadret** [comment]
Guys, I haven't seen any ITP so far for this package on Debian mailing lists. The only attempt I've found so far is this [RFP #592234](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=592234), though I believe this is some other software with the same name.

So, long story short, I was in need for ready-to-use package for Debian, so I built one. You may find it here: [http://deb.ianod.es/debian/pool/main/f/fswatch/](http://deb.ianod.es/debian/pool/main/f/fswatch/). In case you are using Debian, you may use [my repository](http://deb.ianod.es) for ease of installation and future updates. Currently it's amd64 only and I still have couple of things that needs ironing out, but afterwards I will attempt to push it into main repos of Debian.

**Comment by ptarjan** [comment]
:+1:

**Comment by tunezaq** [comment]
@hadret looks like your repository is down :(
```
Err http://deb.ianod.es unstable/main Sources                            
  404  Not Found
Err http://deb.ianod.es unstable/main amd64 Packages
  404  Not Found
Err http://deb.ianod.es unstable/main i386 Packages
  404  Not Found
```

**Comment by emcrisostomo** [comment]
Superseded by #149

**Comment by dialex** [comment]
This issue is still active on #149 and #170.
We still can't install `fswatch` on Ubuntu/Debian...

```
$ sudo apt-get install fswatch
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package fswatch
```

**Comment by hadret** [comment]
Hey guys, apologies for late response. I still got notifications from GitHub, so here's my 5 cents:

1. In the meantime I closed my PPA for Debian, hence the 404 Not Found. (More info here: https://chabik.com/closing-ppa-for-debian/).
2. On my PPA website you can grab the whole repository, including fswatch package and building blocks that can potentially be used for upgrading. (http://deb.ianod.es & http://deb.ianod.es/repo-public.tar.xz).
3. I also extracted repo mentioned in point 2 so you can grab stuff related to fswatch separately from here: http://deb.ianod.es/fswatch.
