### ISSUE TITLE
Misleading output

### ISSUE THREAD

**Issue by walterdolce** [emcrisostomo/fswatch#62]
Hi @emcrisostomo , first of all thank you for providing this useful tool to the community.

I'm using `fswatch` to implement something useful in my domain but I suspect that there might be a bug in it currently?

The output from `fswatch` is somewhat misleading and, unless I'm missing relevant informations, I think that they shouldn't be there given a certain action taken.

When I do:

```
# Launch fswatch
> fswatch  -l 0.1 -r \.idea/ \.git/ -x ./

# Output is: /path/to/file Created IsFile
> touch aa

# Output is: /path/to/file Created Removed IsFile
> rm aa
```

Shouldn't the output from the last command be only `/path/to/file Removed IsFile` instead on the one above?

Version in use is `fswatch 1.4.4`.

**Comment by emcrisostomo** [comment]
I'm closing this issue because it is an effect or the FSEvents behaviour.
