### ISSUE TITLE
Command to show available monitors

### ISSUE THREAD

**Issue by walterdolce** [emcrisostomo/fswatch#69]
Hi @emcrisostomo,

This is now an issue. This is rather a proposal for a new command available when using `fswatch`.

It would be nice to have a command listing all the available monitors. Maybe something like (Mac OS X, Yosemite):

```
> fswatch --monitors (-M)
fsevents_monitor
kqueue_monitor
poll_monitor
```

Utilities/tools depending on `fswatch` could let their users choose the monitor and/or prevent to use one the utility/tool when a monitor is not supported by it.

Cheers!

**Comment by emcrisostomo** [comment]
Resolved in <develop>.
