### ISSUE TITLE
Different output when using -e

### ISSUE THREAD

**Issue by walterdolce** [emcrisostomo/fswatch#71]
Hi @emcrisostomo ,

Not sure whether it's a bug or not and if you're aware of the following. I thought that letting you know would have been better though.

When I:
```
> fswatch  -l 0.1 -r -e -x ./ -m poll_monitor
> touch newfile

# Then I get..
> /the/path
> /the/path/newfile
```

When I, instead (assuming `newfile` doesn't exist yet):
```
> fswatch  -l 0.1 -r -e \.git/ -x ./ -m poll_monitor
> touch newfile

# Then I get..
> /the/path Updated AttributeModified
> /the/path/newfile Created
```

And finally when I (again assuming `newfile` doesn't exist):
```
> fswatch  -l 0.1 -r -x ./ -m poll_monitor
> touch newfile

# Then I get..
> /the/path Updated AttributeModified
> /the/path/newfile Created
```

Note the difference between the first example and the second where `-e` it's there but it's empty.
Is this expected?

Thank you

**Comment by emcrisostomo** [comment]
Hi @walterdolce,

Sorry for the belated answer: in the first example the `-e` option is not empty: `-x` is its value.
