### ISSUE TITLE
Elements exclusion not excluding correctly

### ISSUE THREAD

**Issue by walterdolce** [emcrisostomo/fswatch#72]
Hi @emcrisostomo ,

There's something not working as I would expect when excluding items during the watching.
It seems that `fswatch` takes into account only the first element in the list of items to be excluded. I recall this working as expected when not specifying `-m poll_monitor`.

Commands and output:
```
> fswatch  -l 0.1 -r -e excluded1 excluded2 -x ./ -m poll_monitor
> touch excluded2/file
# Output
/the/path/excluded2 Updated AttributeModified
/the/path/excluded2/file Created

> touch excluded1/file
# Nothing happens

> touch file
> /the/path Updated AttributeModified
> /the/path/file Created
# As expected..
```

Thank you!

**Comment by emcrisostomo** [comment]
You're welcome @walterdolce and sorry for the belated answer: you should use multiple `-e` options to pass multiple exclusion filters (the same is true for `-i`).  Your example should then read:

    fswatch  -e excluded1 -e excluded2 ...
