### ISSUE TITLE
Assertion failed on fsw_destroy_session

### ISSUE THREAD

**Issue by gsamokovarov** [emcrisostomo/fswatch#74]
Hello there,

I'm getting `Assertion failed: (ec == 0), function unlock, file /SourceCache/libcxx/libcxx-120/src/mutex.cpp, line 45` when I try to free a C API monitor session in short time after creation.

I have this snippet that always reproduces the problem on my machine:

```cpp
#include <libfswatch/c/libfswatch.h>

int main(int argc, char *argv[])
{
  for (int i = 0; i < 10000; i++) {
    FSW_HANDLE handle = fsw_init_session();
    fsw_destroy_session(handle);
  }
}
```

**Comment by emcrisostomo** [comment]
Hi @gsamokovarov,

Thanks for the bug report. I've spotted the error in `fsw_destroy_session`: you can grab the `develop` branch if you are in a hurry: I'm preparing a release this afternoon or tomorrow and I'll close this issue afterwards.

**Comment by gsamokovarov** [comment]
I tried the fix and it works for me. Thank you @emcrisostomo!
