### ISSUE TITLE
Event Flags not appearing on OSX 10.10.1

### ISSUE THREAD

**Issue by SnoringFrog** [emcrisostomo/fswatch#76]
Numeric flags seem to work fine, but word-based do not appear for any monitor. Tested while monitoring a directory as well as an individual file. 

fswatch version 1.4.6.

**Comment by emcrisostomo** [comment]
Hi @SnoringFrog, can you confirm you are using the `-x` option?

**Comment by SnoringFrog** [comment]
*facepalm*

Real issue is my inability to read, apparently. I swear I went through the arguments on the man page numerous times looking for such an argument.

**Comment by emcrisostomo** [comment]
No problem @SnoringFrog, it has happened to anybody.
