### ISSUE TITLE
Differences between release and master?

### ISSUE THREAD

**Issue by mralexgray** [emcrisostomo/fswatch#78]
When I clone the master branch.. I stupidly can't figure out how to build things.  I run `autoconf` which bricks with something like 

> autoreconf: Entering directory `.'
> autoreconf: running: autopoint --force
> Can't exec "autopoint": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 345.
> autoreconf: failed to run autopoint: No such file or directory
> autoreconf: autopoint is needed because this package uses Gettext>

_However_, I **can** run `./configure` and all is good in the world if I download the tarred "Release".

This is probably more of a question than an issue (maybe an issue for the documentation), but what script/process is being run to get the `Release` ready..  aka, how do i generate `configure`?

**Comment by emcrisostomo** [comment]
Hi @mralexgray,

Straight out of the `README` file:

> A user who whishes to build `fswatch` should get a [release tarball][release]. A release tarball contains everything a user needs to build `fswatch` on his system, following the instructions detailed in the Installation section below and the `INSTALL` file.
> 
> A developer who wishes to modify `fswatch` should get the sources (either from a source tarball or cloning the repository) and have the GNU Build System installed on his machine.  Please read `README.gnu-build-system` to get further details about how to bootstrap `fswatch` from sources on your machine.
> 
> Getting a copy of the source repository is not recommended unless you are a developer, you have the GNU Build System installed on your machine, and you know how to bootstrap it on the sources.

That is: if it's the first time you are using the GNU Build System, you should read some documentation about it. If you are "only" changing the sources, then you just need to install the GNU Build System in order to bootstrap the project.

[release]: https://github.com/alandipert/fswatch/releases
