### ISSUE TITLE
Documentation needed for fswatch-run-* scripts.

### ISSUE THREAD

**Issue by mralexgray** [emcrisostomo/fswatch#79]
There is neither inline (commented in scripts), `man`-page, or `README` mention of how to use the various `fswatch-run-zsh` et. al scripts.

**Comment by emcrisostomo** [comment]
Hi @mralexgray,

No, there isn't any documentation, the reason being explained in the *Compatibility Issues with fswatch v. 0.x* section of the `README`. To make the long story short: those scripts are provided for backward compatibility and *should* not be used unless you are supporting old scripts using the legacy syntax.
