### ISSUE TITLE
Exclude filter not working with inotify_monitor.

### ISSUE THREAD

**Issue by mikol** [emcrisostomo/fswatch#81]
`fswatch -r ./appserver` produces output with hidden files that I would like to ignore. For example:

```
/home/.../server/views/base.jade
/home/.../server/views/._base.jade
```

When I use an exclude filter – e.g., `fswatch -r -e '\._.*' ./appserver` – the output is unchanged.

I know this filter works because I can use it with the poll monitor – `fswatch -m poll_monitor -r -e '\._.*' ./appserver` – and it does what I expect.

**Comment by emcrisostomo** [comment]
Hi @mikol,

I can't reproduce your issue using the latest available `fswatch`. Also, the matching logic is common for all monitors so it's pretty weird that the same filter configuration works for a monitor but not for another. Please reopen this issue if you confirm it.
