### ISSUE TITLE
-i flag seems to not work

### ISSUE THREAD

**Issue by crimsonkissaki** [emcrisostomo/fswatch#82]
OS X 10.9.5
fswatch version 1.4.6

Using fsevents_monitor

Results with no flags upon save:
./Path/To/Watch/Directory/4913
./Path/To/Watch/Directory/ChangedFile.php
./Path/To/Watch/Directory/ChangedFile.php~
./Path/To/Watch/Directory/ChangedFile.php

-e '\.php$' returns expected results
./Path/To/Watch/Directory/4913
./Path/To/Watch/Directory/ChangedFile.php~

-i '\.php$' returns same results as no flags.

Using poll_monitor

Results with no flags upon save:
./Path/To/Watch/Directory/4913
./Path/To/Watch/Directory/ChangedFile.php
./Path/To/Watch/Directory/ChangedFile.php

-e '\.php$' returns expected results
./Path/To/Watch/Directory

-i '\.php$'
./Path/To/Watch/Directory
./Path/To/Watch/Directory/ChangedFile.php
./Path/To/Watch/Directory/ChangedFile.php

**Comment by emcrisostomo** [comment]
Hi @crimsonkissaki,

Currently the behaviour is this (`fswatch` manual, Sec. 3.7.1):

> As their name indicates, they are used to include and exclude paths from the monitored object list and from resulting events. fswatch processes filters this way:
>  * If a path matches an including filter, the path is accepted no matter any other filter.
>  * If a path matches an excluding filter, the path is rejected.
>  * If a path matches no filters, the path is accepted.
>
> Said another way:
>  * All paths are accepted _by default_, unless an exclusion filter says otherwise.
>  * Inclusion filters may override any other exclusion filter.
>  * The order in the definition of filters in the command line has no effect.

So, the answer is that the behaviour is by design. You can add an exclusion filter matching everything. We may even open another issue and discuss whether this is a sane default (I'm not sure either).

**Comment by crimsonkissaki** [comment]
Just for clarification then. Does that mean that -i filters are pretty much only good for overriding overly greedy -e filters?

**Comment by emcrisostomo** [comment]
You're welcome @crimsonkissaki,

Yes, at the moment it does mean exactly that.

I've been thinking about other filtering algorithms (first filter wins, for example), but at the moment the only implemented behaviour is the aforementioned.

**Comment by crimsonkissaki** [comment]
Awesome. Thank you very much. And thanks for this hugely useful script!

**Comment by emcrisostomo** [comment]
You're welcome! I'm glad it's helpful, thanks for saying so, it's appreciated.

**Comment by mattbishop** [comment]
Please put this behavior in the docs for `-I`; I just spent 30 minutes questioning my skills with regex!

**Comment by emcrisostomo** [comment]
A new behaviour of the filtering logic has been implemented in #381 

This adds an opt-in `--filter-mode=conjunctive` mode. In that mode, include filters define the candidate set, so an include-only command behaves as expected:

```sh
fswatch --filter-mode=conjunctive -i '\.c$' .
```
