### ISSUE TITLE
File System Events monitor broken on OS X Yosemite

### ISSUE THREAD

**Issue by samvv** [emcrisostomo/fswatch#85]
Using fswatch with the default monitor (`fsevents_monitor`) on OS X Yosemite does not produce any output. The `poll_monitor` and `kqueue_monitor` do work.

Related to issue #61, though I tried restarting and it still doesn't work. 

Ouput of `otool -L /usr/local/bin/fswatch`:

````
/usr/local/bin/fswatch:
	/usr/local/Cellar/fswatch/1.4.7/lib/libfswatch.0.dylib (compatibility version 2.0.0, current version 2.0.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 62.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
````

**Comment by emcrisostomo** [comment]
Hi @samvv,

The latest OS X is the current development environment for `fswatch` and I'm not able to reproduce the problem you describe. How did you install `fswatch`?

**Comment by samvv** [comment]
Hmm might be related to my set-up then ... I did a simple `brew install fswatch`.

I solved the issue temporarily by changing the default monitor to `kqueue` with `alias fswatch='fswatch -m kqueue_monitor`.
