### ISSUE TITLE
watch for a specific filetype

### ISSUE THREAD

**Issue by rhacker** [emcrisostomo/fswatch#86]
How can we watch for a specific filetype ? It would be convenient to run the build if that kind of filetype changes only.

Thanks,

**Comment by emcrisostomo** [comment]
Hi,

How do you determine the type of a file? If you use the file extension you can just use inclusion and exclusion patterns.

-- 
Enrico M. Crisostomo

Sent from a mobile device.
Please excuse typos and brevity.

**Comment by rhacker** [comment]
@emcrisostomo yes, it's exactly how it works. Do you have any example of using those ? 
I'm not so sure about the format, what I've tried is : `fswatch -0 -r -o . -i '.js$' | xargs -0 -n 1 -I {} make js  `. It doesn't work, the pattern is not correct I think.

**Comment by emcrisostomo** [comment]
Well, I guess you may check the documentation:

  * `man fswatch`
  * `info fswatch`
  * Use the [PDF manual][pdf].

The short story: `-I` and `-E` can be used to specify inclusion and exclusion filters, that are regular expressions matched against the path of every notification. Citing the documentation:

>  * All paths are accepted *by default*, unless an exclusion filter says otherwise.
>  * Inclusion filters may override any exclusion filter.
>  * The order in the definition of filters in the command line has no effect.

[pdf]: https://drive.google.com/folderview?id=0BxZtP9CHH-Q6bHF3bmJGRmlVcVU&usp=sharing

**Comment by ivarref** [comment]
Hi @rhacker I've made an example at SO for this: http://stackoverflow.com/questions/34713278/fswatch-to-watch-only-a-certain-file-extension/37237522#37237522

**Comment by emcrisostomo** [comment]
Thanks @ivarref, your SO answer is indeed correct.
