### ISSUE TITLE
fswatch running on the background

### ISSUE THREAD

**Issue by meltonpineda** [emcrisostomo/fswatch#89]
Hi,
Is there a flag that will running fswatch as a daemon and it will trigger when a file is modified?

**Comment by meltonpineda** [comment]
can i also do whenever i start my machine they will also automatically start watching my folders?

**Comment by emcrisostomo** [comment]
`fswatch` requires nothing special.  However, `fswatch` just dumps file changes to its output.  If you want to act on those changes you will need to prepare a shell script that does what you want.  You will then configure your OS to launch this script during the boot procedure.  How you accomplish this is system specific: check the documentation of your OS.
