### ISSUE TITLE
Cannot get swatch to monitor folder

### ISSUE THREAD

**Issue by cobyrne09** [emcrisostomo/fswatch#90]
Hey,

Total noob here. I am using fswatch to sync a project folder to a dev server. The goal is to get it to permanently run in the background to monitor changes on the project folder, every time I start up my machine. The shell script handles the syncing. 

I use the following command to try to watch the project folder:

 user$ fswatch /Applications/MAMP/htdocs/tdxall | /usr/local/bin/synctodev.sh

but it only executes my shell script upon entering it in terminal, and it does not continually monitor changes. I would like it to run instantaneously (or within a second) whenever I save a folder. 

From the looks of the documentation, this is what my script should do, but maybe I am missing something obvious. 

Sincere thanks for any help. It is greatly appreciated.

**Comment by emcrisostomo** [comment]
Hi @cobyrne09, I don't know what `synctodev.sh` does, but I guess piping `fswatch` to it won't just do the work. `fswatch` output changes to the output, one per line, or separated as you wish, and your script must be able to receive them somehow and process it.

The documentation offers some example: did you notice this one in the `README`?

```
$ fswatch -0 path | while read -d "" event \
  do \
    // do something with ${event}
  done
```

This example tells `fswatch` to output `NUL`-separated records which are piped and read by the `while` loop (`-d ""` will split records on `NUL`).  Each record, now saved into the `event` variable, can be used as you wish.

Another way to accomplish the same thing is using `xargs`:

> To run a command when a set of change events is printed to standard output but no event details are required, then the following command can be used:
> 
>     $ fswatch -o path | xargs -n1 -I{} program

Everybody please read the [documentation] first: I invest time in writing the `README` and the Texinfo manual.  I'm fine with answering any question, but it would also be really nice if people actually used the documentation.

[documentation]: http://emcrisostomo.github.io/fswatch/documentation.html
