### ISSUE TITLE
cancel current execution after of a new event

### ISSUE THREAD

**Issue by dashaus** [emcrisostomo/fswatch#93]
I have the following script:

```shell
fswatch ts |
while read; do
	echo "changes received";

	echo "compiling typescript files..";
	tsc -p ts/; 
	
	echo "compiling files with babel...";
	babel ES6 -d scripts --babelrc ES6/babelconfig.json;
	
	echo "OK";
done
```

the execution inside of `while` take 15 seconds, I want that when a new event is raised cancel the current execution and execute it again. How can I do? I know really little about shell script...

**Comment by seaside98** [comment]
@dashaus I created something very similar for a project I'm working on. Basically, you find the PID of the running script and kill it. You may need to change the ```"fswatch"```...

```bash
# Find the PIDs
pids=$(ps -ef | grep "fswatch" | grep -v grep | awk '{print $2}')

# Kill them
if [ -n "$pids" ]; then
    kill -9 $pids
fi

# ...
```

**Comment by dashaus** [comment]
And How I can detect when a new event is raised?. Thanks you very much!

**Comment by seaside98** [comment]
@dashaus You will just put that at the beginning of your current script. If any fswatch's are running, they will be stopped, and then yours will be started.

**Comment by seaside98** [comment]
@dashaus Oh, wait. I see what you mean. It will look something like:

```fswatch.bash``` --

```bash
fswatch ts |
while read; do

    # Find the PIDs
    pids=$(ps -ef | grep -E "babel|tsc" | grep -v grep | awk '{print $2}')

    # Kill them
    if [ -n "$pids" ]; then
        kill -9 $pids
    fi

    #Start compiling
   ./compile.bash

done
```

```compile.bash``` --

```bash
echo "changes received";

echo "compiling typescript files..";
tsc -p ts/; 

echo "compiling files with babel...";
babel ES6 -d scripts --babelrc ES6/babelconfig.json;

echo "OK";
```

**Comment by dashaus** [comment]
thanks, then I have this in this moment:

```bash
compile(){
	p "compiling typescript files.." &&
	tsc -p ts/ &&

	p "transpiling files with babel..." &&
	babel -q ES6 -d scripts --babelrc ts/babelconfig.json &&

	p "OK";
	p "waiting for new changes...";
}

compile;

fswatch ts |
while read; do
	# Find the PIDs
    pids=$(ps -ef | grep -E "babel|tsc" | grep -v grep | awk '{print $2}')

    # Kill them
    if [ -n "$pids" ]; then
        kill -9 $pids
    fi

	p "changes received";
	compile;
done
```

And don't works... The problem is that the block inside of `while` It is not executed until the previous iteration ends...

**Comment by dashaus** [comment]
The new event is executed when the previous event ends. I don't know if is possible read the events queue in fswatch

**Comment by emcrisostomo** [comment]
That's expected: `compile` will have to finish before the next `while` iteration is executed. Use:

    compile.sh &

or

    nohup compile.sh &

instead. It's essential for `compile.sh` to be a separate script.

**Comment by dashaus** [comment]
Aaaah, ok. I understand now. The `&` is the key. Finally, I can do it in one file:

```bash
p(){
	now="$(date +'%r')"
	printf "$(tput setaf 1)%s$(tput sgr0) | $(tput bold)$1$(tput sgr0)\n" "$now";
}

compile(){
    p "compiling typescript files.." &&
    tsc -p ts/ &&

    p "transpiling files with babel..." &&
    babel -q ES6 -d scripts --babelrc ts/babelconfig.json &&

    p "OK!" &&
    p "waiting for new changes...";
}

compile &

fswatch ts |
while read; do
    p "new changes received!"

	# Find the PIDs
    pids=$(ps -ef | grep -E "babel|tsc" | grep -v grep | awk '{print $2}')

    # Kill them
    if [ -n "$pids" ]; then
        p "cancelling actual event..."; kill -9 $pids &> /dev/null
    fi

	compile &
done
```

It works like a charm! Thanks you both! :+1:

**Comment by emcrisostomo** [comment]
You're welcome.

I suggested you using a separate script for the compilation job so that it would be easier to isolate its PID and kill it (and its child processes).

I'm glad you've found a working solution.

**Comment by AntoinePrv** [comment]
Hi,
For anyone finding this issue, I've made a minimally reproducible example that also make it easier to track the pid. Feedback is welcome :) 
```bash
long_command(){
	clear
	printf "Starting"
	sleep 1
	printf "."
	sleep 1
	printf "."
	sleep 1
	printf "."
	sleep 1
	printf " done!\n"
}

cancel_and_run() {
	while read; do
		if [ ${command_pid:-0} -gt 0 ]; then
			# Process may not exist anymore
			kill $command_pid &> /dev/null
		fi

		long_command &
		local command_pid=$!
	done
}

fswatch somefile | cancel_and_run
```
