### ISSUE TITLE
Question on lifecycle of watchers and deduplication

### ISSUE THREAD

**Issue by eimajenthat** [emcrisostomo/fswatch#96]
I stumbled across this utility, and it sounds like a perfect solution for my needs.  I have a couple questions though:
1. What's the lifecycle of my watch?  Does it stop watching as soon as the command is closed, or perhaps when my terminal window is closed?  Or is it persisted somewhere that it lasts indefinitely?
2. How does one stop a watch once started?
3. If you create a duplicate watch is there any way to detect the duplication and only keep one?

My use case is this: I have a local directory which I want to rsync to a development box every time a change is made locally.  I want this listener to be always on.  I could add some kind of login script, or add something to my .bashrc, but I also don't want to create a duplicate watch every time I open a terminal.  I found a solution I think will work using launchctl, but I like that your tool is cross-platform, and it's a simple bash command, rather than a weird XML thing.

Anyway, thanks for sharing this nifty utility with the community!

**Comment by emcrisostomo** [comment]
Hi @eimajenthat,

Thank you!

Here are quick answers to your questions:

  * The "watch" runs into the `fswatch` process: as soon as the process terminates so does the watch.
  * Pick your favourite way to terminate a process, being CTRL-C the easiest if you're running `fswatch` in  a terminal.
  * You may have more than one `fswatch` instance running and each one may or may not be watching the same directories. `fswatch` does nothing to detect that situation (assuming you always could). If you are concerned about this possibility you may wrap the `fswatch` invocation into a script that takes care of it (e.g.: using a lock file, keeping track of the directories you are watching, etc). I wouldn't recommend it, though.

Well, if you want the listener to be always on you I'm afraid you have to rely on your OS' facilities to execute a daemon/service/whatever. On OS X a launch agent for your user may be the simpler way to go.
